- name: Ensure services are enabled and started.
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - cups

- name: Ensure sshd service is disabled and stopped.
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - sshd
