- name: Ensure services are enabled.
  ansible.builtin.service:
    become: yes
    name: "{{ item }}"
    enabled: true
    loop:
      - cups.service
      - ntpd.service
      - sxhkd.service

- name: Ensure sshd service is disabled.
  ansible.builtin.service:
    become: yes
    name: sshd.service
    enabled: false
